### ISSUE TITLE
move file issue

### ISSUE THREAD

**Issue by JustGitHubUser** [Xarlot/DXVcs2Git#17]
If a file is autorenamed by git (because of match percent), it does not sync properly.

**Comment by JustGitHubUser** [comment]
It have occured again.
Error: http://ccnet.devexpress.devx/ccnet/server/farm/project/XPF+Diagram+sync+task+v15.2/build/log20160209125150Lbuild.473.xml/ViewBuildReport.aspx
It looks like issue щccures if uyout try to create folder and to move file into this new folder in one merge request.

**Comment by JustGitHubUser** [comment]
It' s always one file and only one file.

**Comment by Xarlot** [comment]
fixed
