### ISSUE TITLE
An autodetected merge comment like "Merge branch 'xxx' into yyy" is unusable

### ISSUE THREAD

**Issue by JustGitHubUser** [Xarlot/DXVcs2Git#19]
We should skip commits with messages like "Merge branch 'xxx' into yyy" while we find appriate message for merge request

**Comment by Xarlot** [comment]
в доступной информации о мерж реквесте без обращения к серверу содержится только последний коммит. 
не мержи ченджи при создании мерж реквеста, тулза умеет это делать сама
